### ISSUE TITLE
Ground Segmentation and Clustering from Point Cloud

### ISSUE THREAD

**Issue by noshluk2** [noshluk2/Research_Projects#2]
## What to do : 
- Read point cloud and segment 
  - Cynlinders
  - Ground plane
  - Walls
- Cluster each of them separately
 
## Generic Steps to Segmentation
1. Pre-process the point cloud data (e.g., denoising, down-sampling, etc.)
2. Apply a segmentation algorithm to divide the point cloud into several clusters (e.g., Euclidean Clustering, SAC-Segmentation, etc.)
3. Extract features from each cluster (e.g., surface normals, curvatures, etc.)
4. Use the extracted features to classify the clusters into different objects or parts
5. Visualize the segmented point cloud and results.

### Documentation links :
- https://pcl.readthedocs.io/projects/tutorials/en/latest/index.html
- https://pcl.readthedocs.io/projects/tutorials/en/latest/voxel_grid.html#voxelgrid
- https://pcl.readthedocs.io/projects/tutorials/en/latest/conditional_euclidean_clustering.html#conditional-euclidean-clustering
- https://pcl.readthedocs.io/projects/tutorials/en/latest/planar_segmentation.html

**Comment by HaiderAbasi** [comment]
![image](https://user-images.githubusercontent.com/49869365/216249719-1936d40a-0dfc-4360-906f-8e72ce22375b.png)
@noshluk2 Issue while Colcon builds on resource nodes!
 Update readme to incorporate ROS linkage method while building.

**Comment by noshluk2** [comment]
Add screen shot of Cmake list as well .

**Comment by noshluk2** [comment]
Remove ROS things from resources so you can understand how PCL is working

**Comment by HaiderAbasi** [comment]
Dated: 6-2-23
- Generated filtered point cloud by configuring in export .pcd in RTABmap
- Removed ROS stuff from cylinder_segmentation and got a basic overview of its working
- Segmented Tabletop + Mug by performing plane & cylinder segmentation using Sample Consensus segmentation 
- Segmented Cloud Plane using Plane Segmentation 

Working on:
- Visualizing segmented plane and cylinder on the same point cloud
- Pillars segmentation using cylinder segmentation in generated point cloud

**Comment by HaiderAbasi** [comment]
Dated: 7-2-23

- Plane & Cylindrical Segmentation
  1. Table and mug scene
       
<p align="center">
<img src="https://user-images.githubusercontent.com/49869365/217147839-67b13c55-e61c-4a9f-97a4-8fdef74e5b73.png" width="300" height="300">
</p>

  2. Ground and Pillars
       
<p align="center">
<img src="https://user-images.githubusercontent.com/49869365/217149147-19c42bee-aa2a-41d5-8510-009631c46120.png" width="300" height="300">
</p>

> Insight: Modifying Cylinder hyperparameters was not enough to yield segmented pillars. Instead, wall or walls were being segmented. One possible thing to try could be limiting cylindrical segmentation to area bounded by the segmented plane (Ground)

- Cluster Extraction
  1. Table scene lms400
       
<p align="center">
<img src="https://user-images.githubusercontent.com/49869365/217149932-ae58e073-6c30-4240-8c9e-cb7bf6ee9692.png" width="300" height="300">
</p>


  2. Walls and Pillars
       
<p align="center">
<img src="https://user-images.githubusercontent.com/49869365/217150048-e2979644-f42f-4863-8e6c-213baf93fcdd.png" width="300" height="300">
</p>

**Comment by noshluk2** [comment]
Nice .
Kindly close the issue with a commit .

**Comment by HaiderAbasi** [comment]
Dated: 8-2-23
   >  _ 7 - 8 _ :sleeping_bed:
   >  _ 9 - 2 _ :candle:

- Region Growing Segmentation (Hyperparameters tuned)
  1. Pillars + Walls & Ground
       > Neighbors = 20
       > smoothness thresh = 7 rad
       > curvature thresh = 10
<p align="center">
<img src="https://user-images.githubusercontent.com/49869365/217485331-2efecb62-11f8-4905-9f19-0b876f0b13d2.png" width="300" height="300">
</p>

**Comment by HaiderAbasi** [comment]
Dated: 9-2-23

- Segmentation Pipeline
  1. Ground + Pillars + Wall segmented
       > Stage 1: Ground segmented and filtered using planar segmentation
       > Stage 2: Pillars segmented and filtered one by one by cylindrical segmentation
       > Stage 3: Walls segmented and saved as the last remaining points in the point cloud 
<p align="center">
<img src="https://user-images.githubusercontent.com/49869365/217724445-08a07305-4d07-4332-aa29-f43c880e4456.png" width="400" height="300">
</p>
